### ISSUE TITLE
dotnet swagger tofile give error since v3.0.2

### ISSUE THREAD

**Issue by SteeveGL** [Havunen/DotSwashbuckle#5]
### v3.0.1
`dotnet swagger tofile --yaml --output openapi.json myproject.dll v1`
```
Swagger JSON/YAML successfully written to /App/openapi.json
```

### v3.0.2+
`dotnet swagger tofile --yaml --output openapi.json myproject.dll v1`
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'DotSwashbuckle.AspNetCore.Swagger, Version=3.0.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

@Havunen You should use Tags and PRs. You spam the project with commits. It's going to be hard to diagnose.

**Comment by SteeveGL** [comment]
It may relate to that change:
https://github.com/Havunen/DotSwashbuckle/commit/ac50b8916f8ce02c502a62379ec4adce3564c15b#diff-d9125c66d4c042c4f6320e6752dde14dfab438bfd620ba4b138ed51902fff6d3R96

Tomorrow could try to debug the project.

**Comment by Havunen** [comment]
I had to redo the whole fork due to complains about commit history.
Because of that I had to re-apply all the patches again on top of the new fork, maybe this is the spam you are referring to. Sorry about that. 
You can check the changes between versions from the previous repo: https://github.com/Havunen/DotSwashbuckle2

**Comment by Havunen** [comment]
About the actual issue, did you verify that you have same version of the CLI program and Nuget installed? They both should be 3.0.3

By looking at the error message you posted I dont understand why it looking for assembly 3
0.2

Edit: ah you mean 3.0.2 broke it, ok.

**Comment by SteeveGL** [comment]
I used the same version in the project and the CLI and it fix it.

Braking change in Patch version is a little bit hardcore...

**Comment by Havunen** [comment]
Yeah the problem origins from Swashbuckle.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2666 

Do you know how it could be avoided to not throw exception if assembly versions dont match? Maybe we could experiment if opening nuget dependency range is enough to satisfy runtime?
